version: '3'
services:
    # to host online, add caddy to this setup and configure the reverse proxy
    gobitrage_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: gobitrage_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "${PORT:-8000}:${PORT:-8000}"
        env_file:
            - .env
        environment:
            - COMPOSER_ALLOW_SUPERUSER=1
            - APP_ENV=production
            - DB_HOST=${DB_HOST}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - gobitrage_db
        command: ["./serve"]
        networks:
            - gobitrage_network

    gobitrage_db:
        image: mysql:5.7
        container_name: gobitrage_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: gobitrage_database
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: gobitrage_user
            MYSQL_PASSWORD: gobitrage_pass
        ports:
            - "3307:3306" # to avoid conflict with the system mysql
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - gobitrage_network

volumes:
    dbdata:
        driver: local

networks:
    gobitrage_network:
        driver: bridge
