version: '3'
services:
    # to host online, add caddy to this setup and configure the reverse proxy
    gobitrage_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: gobitrage_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "${PORT:-8000}:${PORT:-8000}"
        env_file:
            - .env
        environment:
            - COMPOSER_ALLOW_SUPERUSER=1
            - APP_ENV=production
            - DB_CONNECTION=mysql
            - DB_HOST=${DB_HOST}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        command: ["./serve"]
        networks:
            - gobitrage_network

volumes:
    dbdata:
        driver: local

networks:
    gobitrage_network:
        driver: bridge
